// +build old,!new

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structs.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskStatsResponse struct {
	Stats                *TaskStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskStatsResponse) Reset()         { *m = TaskStatsResponse{} }
func (m *TaskStatsResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatsResponse) ProtoMessage()    {}
func (*TaskStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e774e8f5f348d14d, []int{0}
}

func (m *TaskStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatsResponse.Unmarshal(m, b)
}
func (m *TaskStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatsResponse.Marshal(b, m, deterministic)
}
func (m *TaskStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatsResponse.Merge(m, src)
}
func (m *TaskStatsResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatsResponse.Size(m)
}
func (m *TaskStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatsResponse proto.InternalMessageInfo

func (m *TaskStatsResponse) GetStats() *TaskStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type TaskStats struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskStats) Reset()         { *m = TaskStats{} }
func (m *TaskStats) String() string { return proto.CompactTextString(m) }
func (*TaskStats) ProtoMessage()    {}
func (*TaskStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e774e8f5f348d14d, []int{1}
}

func (m *TaskStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStats.Unmarshal(m, b)
}
func (m *TaskStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStats.Marshal(b, m, deterministic)
}
func (m *TaskStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStats.Merge(m, src)
}
func (m *TaskStats) XXX_Size() int {
	return xxx_messageInfo_TaskStats.Size(m)
}
func (m *TaskStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStats.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStats proto.InternalMessageInfo

func (m *TaskStats) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskStats) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskStatsResponse)(nil), "hashicorp.nomad.plugins.drivers.proto.TaskStatsResponse")
	proto.RegisterType((*TaskStats)(nil), "hashicorp.nomad.plugins.drivers.proto.TaskStats")
}

func init() {
	proto.RegisterFile("structs.proto", fileDescriptor_e774e8f5f348d14d)
}

var fileDescriptor_e774e8f5f348d14d = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xe9, 0x82, 0xc2, 0x46, 0x14, 0xdc, 0x53, 0xe9, 0xc5, 0xb2, 0x20, 0x78, 0x9a, 0x15,
	0xbd, 0x08, 0xde, 0x3c, 0xf8, 0x03, 0xd6, 0x7a, 0xd1, 0x53, 0xb2, 0x9b, 0x66, 0x87, 0x36, 0x99,
	0x90, 0x99, 0xf8, 0xfb, 0xc5, 0xac, 0x6d, 0xaf, 0x3d, 0xce, 0xe3, 0x9b, 0xf7, 0x3e, 0x75, 0xcd,
	0x92, 0xf2, 0x20, 0x0c, 0x31, 0x91, 0x50, 0x73, 0x3f, 0x69, 0x9e, 0x70, 0xa0, 0x14, 0x21, 0x90,
	0xd7, 0x23, 0xc4, 0x7d, 0x76, 0x18, 0x18, 0xc6, 0x84, 0x3f, 0x36, 0xfd, 0x63, 0xab, 0x3b, 0x47,
	0xe4, 0xf6, 0xb6, 0x2b, 0x97, 0xc9, 0xdb, 0x4e, 0xd0, 0x5b, 0x16, 0xed, 0xe3, 0x0c, 0xb4, 0xdf,
	0xea, 0x76, 0xa3, 0x79, 0xf7, 0x21, 0x5a, 0xb8, 0xb7, 0x1c, 0x29, 0xb0, 0x6d, 0xde, 0xd5, 0x05,
	0xff, 0x05, 0xcb, 0xc5, 0x7a, 0xf1, 0x70, 0xf5, 0xf4, 0x08, 0x67, 0x8d, 0xc1, 0xa9, 0x68, 0x7e,
	0x6f, 0x3f, 0x55, 0x7d, 0xcc, 0x9a, 0x1b, 0x55, 0xe1, 0x58, 0x1a, 0xeb, 0xbe, 0xc2, 0xb1, 0x79,
	0x51, 0xf5, 0x51, 0x66, 0x59, 0x95, 0xa1, 0x15, 0xcc, 0xba, 0x70, 0xd0, 0x85, 0xcd, 0x81, 0xe8,
	0x4f, 0xf0, 0x5b, 0xfb, 0xb5, 0x76, 0x28, 0x53, 0x36, 0x30, 0x90, 0xef, 0xc4, 0x25, 0x62, 0xee,
	0x4c, 0xde, 0x9a, 0x64, 0xf5, 0x8e, 0x5f, 0xbd, 0xc6, 0x60, 0x2e, 0x4b, 0xc5, 0xf3, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x86, 0x6a, 0x0c, 0x89, 0x37, 0x01, 0x00, 0x00,
}
